# -*- coding: utf-8 -*-
"""Diabetes Analysis_Project 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XOuvX50vfusS3QXIMm105w07rO9eIw5G
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load the dataset from the link in the assignment
url = "https://raw.githubusercontent.com/niteen11/DataAnalyticsAcademy/master/Python/dataset_diabetes/diabetic_data.csv"
df = pd.read_csv(url)

print("First rows of the dataset:")
df.head()

# Cleaning task: keep only Male and Female
df_clean = df[df['gender'].isin(['Male', 'Female'])].copy()

# Make sure time_in_hospital is numeric
df_clean['time_in_hospital'] = pd.to_numeric(df_clean['time_in_hospital'], errors='coerce')
df_clean = df_clean.dropna(subset=['time_in_hospital'])

# Separate groups
male = df_clean[df_clean['gender'] == 'Male']
female = df_clean[df_clean['gender'] == 'Female']

# Descriptive statistics
summary = df_clean.groupby('gender')['time_in_hospital'].agg(['count', 'mean', 'median', 'min', 'max', 'std'])
summary

# Visualization
means = summary['mean']
plt.bar(means.index, means.values)
plt.title("Average Time in Hospital by Gender")
plt.xlabel("Gender")
plt.ylabel("Average days in hospital")
plt.show()

# Conclusion
male_mean = means.loc['Male']
female_mean = means.loc['Female']

print("Conclusion:")
print(f"Male patients stayed an average of {male_mean:.2f} days in the hospital, "
      f"while female patients stayed an average of {female_mean:.2f} days. "
      "This suggests a small difference in hospital stay length by gender. "
      "However, this analysis does not control for age or severity of illness.")

# =========================
# EXTRA ANALYSIS 1: Lab procedures
# =========================

summary_labs = df_clean.groupby('gender')['num_lab_procedures'].mean()
summary_labs

plt.bar(summary_labs.index, summary_labs.values)
plt.title("Average Number of Lab Procedures by Gender")
plt.xlabel("Gender")
plt.ylabel("Average lab procedures")
plt.show()


# =========================
# EXTRA ANALYSIS 2: Medications
# =========================

summary_meds = df_clean.groupby('gender')['num_medications'].mean()
summary_meds

plt.bar(summary_meds.index, summary_meds.values)
plt.title("Average Number of Medications by Gender")
plt.xlabel("Gender")
plt.ylabel("Average medications")
plt.show()
print("Conclusion:")
print(f"The average time in hospital for male and female patients was very similar."
      f"This indicates that both groups receive comparable hospital treatment in this dataset."
      f"This suggests a small difference in hospital stay length by gender.")

# =========================
# COMBINED ANALYSIS: Age + Insulin
# =========================

# Select only two age groups for clarity
df_combo = df_clean[df_clean['age'].isin(['[30-40)', '[70-80)'])].copy()

# Create insulin group column
df_combo['insulin_group'] = df_combo['insulin'].apply(lambda x: 'With Insulin' if x != 'No' else 'No Insulin')

# Calculate mean number of medications
combo_summary = df_combo.groupby(['age', 'insulin_group'])['num_medications'].mean().unstack()
combo_summary
combo_summary.plot(kind='bar')
plt.title("Average Number of Medications by Age and Insulin Use")
plt.xlabel("Age group")
plt.ylabel("Average number of medications")
plt.show()
print("Conclusion:")
print(f"The results show that both age and insulin use are associated with higher medication counts. Older patients use more medications than younger patients, and within each age group, patients who receive insulin use more medications than those who do not. However, this analysis does not control for disease severity or other health conditions.")